### PR TITLE
Fix aws-cli install failure

### PR DESCRIPTION
**Pull request by krazijames**
In some cases, only Python 3 is installed and installing `aws-cli` is fail due to its dependency on Python 2.

### CODE REVIEW

**Comment by imkitae** [comment]
aws-cli depends on Python 2.6.5+ or 3.3+
https://docs.aws.amazon.com/cli/latest/userguide/installing.html

Which failure cases do you mean?

**Comment by krazijames** [comment]
@imkitae In `Dockerfile`, `RUN curl https://bootstrap.pypa.io/get-pip.py | python \` uses `python` and there must be `python` installed. But in the case of building on Travis CI with php 7.2 or building on local machine, system cannot find `python` command because only `python3` is installed in those cases.

**Comment by imkitae** [comment]
Oh, I missread the context. You mean installing aws-cli is failed, not aws-cli itself.. I understand.

**Review by imkitae — APPROVED** [review]

**Comment by krazijames** [comment]
@imkitae By the way, just replacing command `python` with `python3` looks fine instead of installing missing `python`. Isn't it better?

**Pull request merged**
